version: '3.4'

services:
  fastify-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: "no"
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - fastify-example-network

  mongo-bd:
    image: mongo
    restart: "no"
    ports:
      - 27017:27017
    volumes:
      - dbvolume:/data
    environment: {
      AUTH: "no"
    }
    networks:
      - fastify-example-network

#Networks
networks:
  fastify-example-network:
    driver: bridge
    
volumes:
  node_modules:
  dbvolume: 
    driver: local
